ARCH = SOL
MACHINE = SOL
HOME = /d/hif-users/grote
PYVERS = 1.5
PYTHON = /d/cs-10/vol.sun4.sos5/pub/python-1.5.2
PYWRAPPERHOME = $(HOME)/pywrapper
PYWRAPPERARGS =
OPT = -fast -xtarget=generic
#OPT = -g -dalign -f
POPT = -dalign -f
PYMODULEOPT = 
F90FREE = f90 -e -r8const -u
F90FIXED = f90 -e -r8const -u
CC = cc
SO = sl
LD = f90 -e -r8const $(OPT)
FORTLIB =
LINKLIB =
DLLIB =
XLIB = -L/usr/lib/X11R6
PACTLIB = -L/d/cs-10/vol.sun4.sos5/pub/pact-031699/lib
YORICKLIB = -L/d/cs-10/vol.sun4.sos5/pub/yorick-1.4/lib/yorick/1.4/lib
TCLLIB = 
LAPACKLIB = -L/d/hif-users/grote/lapack/LAPACK
NUMPYINCLUDE = 
OLD = OLD1

WARPSCRIPTS = $(HOME)/scriptsnew
OTHERLIBS = $(PACTLIB) -lpdb -lpml -lscore \
            $(YORICKLIB) -lgist \
            $(LAPACKLIB) -llapack -lblas
#           $(TCLLIB) -ltcl8.0 -ltk8.0

warp:build_static

include Makefile.dependencies

RANFOBJ = $(PYTHON)/Modules/ranf.o $(PYTHON)/Modules/pmath_rng.o
RANFSRC = 

build_static: $(MODULEOBJECTS) $(WARPOBJECTS) config.o pypdbmodule.o
	$(LD) -o pywarp90 $(PYTHONOBJ) $(WARPOBJECTS) $(MODULEOBJECTS) config.o pypdbmodule.o -L$(PYTHON)/lib/python1.5/config -lpython1.5 $(NUMPY) $(OTHERLIBS) -lX11 -lc -lsocket -ldl -lnsl -lm

pypdbmodule.o:pypdbmodule.c
	$(CC) -O -c pypdbmodule.c $(INCLUDE) -I$(PACT)/include

