ARCH = SOL
MACHINE = SOL
HOME = /d/hif-users/grote
PYVERS = 1.5
PYTHON = /d/cs-10/vol.sun4.sos5/pub/python-1.5.2
PYMAC = $(HOME)/pywrapper/pymac.py --f90 -t $(MACHINE)
PYCTOF = $(HOME)/pywrapper/pyctof.py
OPT = -fast
#OPT = -g -dalign -f
POPT = -dalign -f
PYMODULEOPT = 
F90FREE = f90 -e -r8const
F90FIXED = f90 -e -r8const
CC = cc
SO = sl
LD = f90 -e -r8const $(OPT)
FORTLIB =
LINKLIB =
DLLIB =
XLIB = -L/usr/lib/X11R6
PACTLIB = -L/d/cs-10/vol.sun4.sos5/pub/pact-031699/lib
YORICKLIB = -L/d/cs-10/vol.sun4.sos5/pub/yorick-1.4/lib/yorick/1.4/lib
TCLLIB = 
LAPACKLIB = -L/d/hif-users/grote/lapack/LAPACK
NUMPYINCLUDE = 
OLD = OLD1

WARPSCRIPTS = $(HOME)/scriptsnew
INCLUDE = -I$(PYTHON)/include/python$(PYVERS)
PYTHONLIB = -L$(PYTHON)/lib/python$(PYVERS)/config -lpython$(PYVERS)
PYTHONOBJ = $(PYTHON)/lib/python$(PYVERS)/config/python.o
OTHERLIBS = $(PACTLIB) -lpdb -lpml -lscore \
            $(YORICKLIB) -lgist \
            $(LAPACKLIB) -llapack -lblas
#           $(TCLLIB) -ltcl8.0 -ltk8.0
RANFOBJ = $(PYTHON)/Modules/ranf.o $(PYTHON)/Modules/pmath_rng.o
RANFSRC = 

SHAREDOBJECTS = envpy.$(SO) frzpy.$(SO) wxypy.$(SO) f3dpy.$(SO) fxypy.$(SO) \
                w3dpy.$(SO) toppy.$(SO) wrzpy.$(SO) cirpy.$(SO) herpy.$(SO) \
                pybasisC.$(SO)

WARPOBJECTS = env.o \
              frz.o \
              wxy.o \
              f3d.o \
              fxy.o \
              util.o \
              w3d.o \
              dtop.o \
              f3d_mgrid.o \
              dw3d.o \
              dwrz.o \
              fft.o \
              top.o \
              wrz.o \
              cir.o \
              her.o


MODULEOBJECTS = toppymodule.o envpymodule.o w3dpymodule.o f3dpymodule.o \
                wxypymodule.o fxypymodule.o wrzpymodule.o frzpymodule.o \
                cirpymodule.o herpymodule.o \
                top.p.o env.p.o w3d.p.o f3d.p.o wxy.p.o fxy.p.o \
                wrz.p.o frz.p.o \
                cir.p.o her.p.o pybasisC.o
MODULESOURCES = toppymodule.c envpymodule.c w3dpymodule.c f3dpymodule.c \
                wxypymodule.c fxypymodule.c wrzpymodule.c frzpymodule.c \
                cirpymodule.c herpymodule.c \
                pybasisC.c

warp: $(MODULEOBJECTS) $(WARPOBJECTS) config.o pypdbmodule.o
	$(LD) -o pywarp $(PYTHONOBJ) $(WARPOBJECTS) $(MODULEOBJECTS) config.o pypdbmodule.o -L$(PYTHON)/lib/python1.5/config -lpython1.5 $(NUMPY) $(OTHERLIBS) -lX11 -lc -lsocket -ldl -lnsl -lm

warpshared: $(SHAREDOBJECTS)
	#cp *.$(SO) $(WARPSCRIPTS)
	#tar czf linuxpywarpso.tgz *.so
	#scp linuxpywarpso.tgz ife1:pub

pypdbmodule.o:pypdbmodule.c
	$(CC) -O -c pypdbmodule.c $(INCLUDE) -I$(PACT)/include

config.o:config.c
	$(CC) -c config.c $(INCLUDE)

pybasisC.$(SO):pybasisC.o 
	$(LD) -o pybasisC.$(SO) pybasisC.o $(RANFOBJ) $(INCLUDE) $(OTHERLIBS)
	#$(LD) -o pybasisC.$(SO) pybasisC.o $(FORTLIB)
pybasisC.o:pybasisC.c
	$(CC) -g -c pybasisC.c $(INCLUDE) $(NUMPYINCLUDE)
pybasisC.c:$(HOME)/pywrapper/pybasisC.m pybasis.h
	cp $(HOME)/pywrapper/pybasisC.m .
	$(PYCTOF) --f90 -t$(ARCH) pybasisC
pybasis.h:$(HOME)/pywrapper/pybasis.h
	cp $(HOME)/pywrapper/pybasis.h pybasis.h

toppy.$(SO):toppymodule.o top.p.o top.o dtop.o fft.o util.o
	$(LD) -o toppy.$(SO) toppymodule.o top.p.o top.o dtop.o fft.o util.o -lm $(XLIB) -lX11 $(INCLUDE) $(OTHERLIBS) $(DLLIB) $(FORTLIB)

top.p.o:top.p.F90
	$(F90FREE) $(POPT) -c top.p.F90
top.o:top.F top.p.o
	$(F90FIXED) $(OPT) -c top.F
dtop.o:dtop.F top.p.o
	$(F90FIXED) $(OPT) -c dtop.F
fft.o:fft.f
	$(F90FIXED) $(OPT) -c fft.f
util.o:util.f
	$(F90FIXED) $(OPT) -c util.f

toppymodule.o:toppymodule.c pybasis.h
	$(CC) $(PYMODULEOPT) -c toppymodule.c $(INCLUDE) $(NUMPYINCLUDE)
toppymodule.c top.p.F90:top.v
	$(PYMAC) -a top.v

envpy.$(SO):envpymodule.o env.p.o env.o
	$(LD) -o envpy.$(SO) envpymodule.o env.p.o env.o -lm $(XLIB) -lX11 $(INCLUDE) $(OTHERLIBS) $(DLLIB) $(FORTLIB)

env.p.o:env.p.F90
	$(F90FREE) $(POPT) -c env.p.F90
env.o:env.F env.p.o top.p.o
	$(F90FIXED) $(OPT) -c env.F

envpymodule.o:envpymodule.c pybasis.h
	$(CC) $(PYMODULEOPT) -c envpymodule.c $(INCLUDE) $(NUMPYINCLUDE)
envpymodule.c env.p.F90:env.v
	$(PYMAC) -a env.v top.v


w3dpy.$(SO):w3dpymodule.o w3d.p.o w3d.o dw3d.o
	$(LD) -o w3dpy.$(SO) w3dpymodule.o w3d.p.o w3d.o dw3d.o -lm $(XLIB) -lX11 $(INCLUDE) $(OTHERLIBS) $(DLLIB) $(FORTLIB)

w3d.p.o:w3d.p.F90
	$(F90FREE) $(POPT) -c w3d.p.F90
w3d.o:w3d.F w3d.p.o top.p.o
	$(F90FIXED) $(OPT) -c w3d.F
dw3d.o:dw3d.F w3d.p.o top.p.o
	$(F90FIXED) $(OPT) -c dw3d.F

w3dpymodule.o:w3dpymodule.c pybasis.h
	$(CC) $(PYMODULEOPT) -c w3dpymodule.c $(INCLUDE) $(NUMPYINCLUDE)
w3dpymodule.c w3d.p.F90:w3d.v
	$(PYMAC) -a w3d.v top.v


f3dpy.$(SO):f3dpymodule.o f3d.p.o f3d.o f3d_mgrid.o
	$(LD) -o f3dpy.$(SO) f3dpymodule.o f3d.p.o f3d.o f3d_mgrid.o -lm $(XLIB) -lX11 $(INCLUDE) $(OTHERLIBS) $(DLLIB) $(FORTLIB)

f3d.p.o:f3d.p.F90
	$(F90FREE) $(POPT) -c f3d.p.F90
f3d.o:f3d.F f3d.p.o top.p.o
	$(F90FIXED) $(OPT) -c f3d.F
f3d_mgrid.o:f3d_mgrid.F f3d.p.o top.p.o
	$(F90FIXED) $(OPT) -c f3d_mgrid.F

f3dpymodule.o:f3dpymodule.c pybasis.h
	$(CC) $(PYMODULEOPT) -c f3dpymodule.c $(INCLUDE) $(NUMPYINCLUDE)
f3dpymodule.c f3d.p.F90:f3d.v
	$(PYMAC) -a f3d.v top.v

wrzpy.$(SO):wrzpymodule.o wrz.p.o wrz.o dwrz.o
	$(LD) -o wrzpy.$(SO) wrzpymodule.o wrz.p.o wrz.o dwrz.o -lm $(XLIB) -lX11 $(INCLUDE) $(OTHERLIBS) $(DLLIB) $(FORTLIB)

wrz.p.o:wrz.p.F90
	$(F90FREE) $(POPT) -c wrz.p.F90
wrz.o:wrz.F wrz.p.o top.p.o
	$(F90FIXED) $(OPT) -c wrz.F
dwrz.o:dwrz.F wrz.p.o top.p.o
	$(F90FIXED) $(OPT) -c dwrz.F

wrzpymodule.o:wrzpymodule.c pybasis.h
	$(CC) $(PYMODULEOPT) -c wrzpymodule.c $(INCLUDE) $(NUMPYINCLUDE)
wrzpymodule.c wrz.p.F90:wrz.v
	$(PYMAC) -a wrz.v top.v


frzpy.$(SO):frzpymodule.o frz.p.o frz.o
	$(LD) -o frzpy.$(SO) frzpymodule.o frz.p.o frz.o -lm $(XLIB) -lX11 $(INCLUDE) $(OTHERLIBS) $(DLLIB) $(FORTLIB)

frz.p.o:frz.p.F90
	$(F90FREE) $(POPT) -c frz.p.F90
frz.o:frz.F frz.p.o top.p.o
	$(F90FIXED) $(OPT) -c frz.F

frzpymodule.o:frzpymodule.c pybasis.h
	$(CC) $(PYMODULEOPT) -c frzpymodule.c $(INCLUDE) $(NUMPYINCLUDE)
frzpymodule.c frz.p.F90:frz.v
	$(PYMAC) -a frz.v top.v


wxypy.$(SO):wxypymodule.o wxy.p.o wxy.o
	$(LD) -o wxypy.$(SO) wxypymodule.o wxy.p.o wxy.o -lm $(XLIB) -lX11 $(INCLUDE) $(OTHERLIBS) $(DLLIB) $(FORTLIB)

wxy.p.o:wxy.p.F90
	$(F90FREE) $(POPT) -c wxy.p.F90
wxy.o:wxy.F wxy.p.o top.p.o w3d.p.o
	$(F90FIXED) $(OPT) -c wxy.F

wxypymodule.o:wxypymodule.c pybasis.h
	$(CC) $(PYMODULEOPT) -c wxypymodule.c $(INCLUDE) $(NUMPYINCLUDE)
wxypymodule.c wxy.p.F90:wxy.v
	$(PYMAC) -a wxy.v top.v


fxypy.$(SO):fxypymodule.o fxy.p.o fxy.o
	$(LD) -o fxypy.$(SO) fxypymodule.o fxy.p.o fxy.o -lm $(XLIB) -lX11 $(INCLUDE) $(OTHERLIBS) $(DLLIB) $(FORTLIB)

fxy.p.o:fxy.p.F90
	$(F90FREE) $(POPT) -c fxy.p.F90
fxy.o:fxy.F fxy.p.o top.p.o
	$(F90FIXED) $(OPT) -c fxy.F

fxypymodule.o:fxypymodule.c pybasis.h
	$(CC) $(PYMODULEOPT) -c fxypymodule.c $(INCLUDE) $(NUMPYINCLUDE)
fxypymodule.c fxy.p.F90:fxy.v
	$(PYMAC) -a fxy.v top.v


cirpy.$(SO):cirpymodule.o cir.p.o cir.o
	$(LD) -o cirpy.$(SO) cirpymodule.o cir.p.o cir.o -lm $(XLIB) -lX11 $(INCLUDE) $(OTHERLIBS) $(DLLIB) $(FORTLIB)

cir.p.o:cir.p.F90
	$(F90FREE) $(POPT) -c cir.p.F90
cir.o:cir.F cir.p.o top.p.o
	$(F90FIXED) $(OPT) -c cir.F

cirpymodule.o:cirpymodule.c pybasis.h
	$(CC) $(PYMODULEOPT) -c cirpymodule.c $(INCLUDE) $(NUMPYINCLUDE)
cirpymodule.c cir.p.F90:cir.v
	$(PYMAC) -a cir.v top.v


herpy.$(SO):herpymodule.o her.p.o her.o
	$(LD) -o herpy.$(SO) herpymodule.o her.p.o her.o -lm $(XLIB) -lX11 $(INCLUDE) $(OTHERLIBS) $(DLLIB) $(FORTLIB)

her.p.o:her.p.F90
	$(F90FREE) $(POPT) -c her.p.F90
her.o:her.F her.p.o top.p.o
	$(F90FIXED) $(OPT) -c her.F

herpymodule.o:herpymodule.c pybasis.h
	$(CC) $(PYMODULEOPT) -c herpymodule.c $(INCLUDE) $(NUMPYINCLUDE)
herpymodule.c her.p.F90:her.v
	$(PYMAC) -a her.v top.v


clean:
	rm -f *.mod *.o *.p.F90 *module.c *.scalars *.$(SO) pybasis*
